### ISSUE TITLE
ChromosomWidget as QGraphicsItem

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#10]
It may be greate to have Chromosom draw as a QGraphicsItem. And then, mouse hover on each part of chromosom would highlight the label name

**Comment by ikit** [comment]
When we discussed about region yesterday you told me that the notion of "region" is not the most important for biologists ...  I propose to stay with "simple flat drawing" for the browser, region's emphasis can be done in another manner (with a kind of label following the cusor by example)

**Comment by dridk** [comment]
Yes, I think it would be enough ! Just a tooltip when you move over region. But actually it's not a prioritary
