### ISSUE TITLE
BaseToPixel class convertor

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#15]
What about create a class to do easily base to pixel conversion. Same for pixel to base.  we may add it into Section class.. 
I have no idea how to implement this ! 
Do you have suggestion ?

**Comment by ikit** [comment]
I think that it's not necessary (the coeff to convert base to pixel is easy to obtain (width/bases) ... 
Let's let each track manage them self how to draw their data... we will see later if we need to improve some calculs
