### ISSUE TITLE
Init using IUPAC table in cpp

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#16]
In Sequence.cpp, Please update static table initialization like this : 
https://github.com/BIG-Tools/BigBrowser/blob/natir/src/core/sequence.cpp

**Comment by natir** [comment]
Wheel

I theory tablular is faster than associative map, one + operation is faster than all other operation, and no possible collision.

I practice you can see my project [better_rev_comp](https://github.com/natir/better_rev_comp) and [bench_rev_comp](https://github.com/natir/bench_rev_comp).

Thank for your review

Ps: Sorry about early push it was a mistake (never work one master, never work one master, repeat after me :))

**Comment by natir** [comment]
We close this issue, implementation isn't clean but see #17
