### ISSUE TITLE
Sequence should inherits from QByteArray

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#18]
For more convenance and beneficts features from QByteArray.

**Comment by natir** [comment]
It's maybe not recommand because destructor of QByteArray isn't virtual.

Documentation : http://doc.qt.io/qt-5/qbytearray.html#dtor.QByteArray
Why destructor need to be virtual : http://stackoverflow.com/questions/461203/when-to-use-virtual-destructors

**Comment by dridk** [comment]
Thanks, i never figure out about this problem.
But There is nothing to delete in sequence class. So the parent destructor
is enough.

**Comment by natir** [comment]
You know the future ? Maybe we need add something required to use destructor, i'm not sure benefit is upper than problem.

And if Sequence inherit to QByteArray, sequence expose too more functionality.

**Comment by dridk** [comment]
Thats mean we should recreate many methods and operator.
But I agree.. let's see which methods we are using and change if necessary

**Comment by dridk** [comment]
At the end, they are more advantage from my point of view to inherits Sequence from QByteArray. This allows to use all feature from QByteArray in sequence. 

```
 seq->count() // With inheritance
 seq->byteArray()->count  // Without inheritance 
```

**Comment by natir** [comment]
I found a solution create a typename Sequence to BytesString.

Advantage :
- We can use all BytesString member
- no duplicate code
- in future if we want use another containers for user is transparent (if we rewrite lost functions)
- no inherite problem

Problem :
- all BytesString membre is expos and we need maintened this in future
- we can't add biological function in class but I think we taf use static function

**Comment by dridk** [comment]
I read the qt guidline which say to not inhertits from object like
QBytearray.
So you were right. I apology.  Then as yoy said, wee are going to add
methods one by one if necessary.

If you have time, please add the following methods for now.
count()
toString ()
toByteArray ()
And everything you thinks its important.
You  may have a look from BioSeq

**Comment by natir** [comment]
Please see, new_sequence branch (not all function is implement but the main part is). 

I think is the better solution one some issue about sequence (#43 #44 ).

Sequence is just a typedef of QByteArray and all function around Sequence is template.

This function accept container like stl type, QString and QByteArray  is stl like container (and maybe all main Qt container but I not check).

Can you test the compilation on windows and merge it in master if all is okay ?

**Comment by dridk** [comment]
Compile on windows 7. You can merge

**Comment by dridk** [comment]
Sorry, but could you check this issue before merging , please ?  #54

**Comment by natir** [comment]
Solve by 4d0184c
