### ISSUE TITLE
import Quazip into the project

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#19]
IGV use a kind of genom data file. A small zip file which contains : cytoband.txt , refSeq.txt and other properties files. 
It would be greate  to include source code in the project from http://quazip.sourceforge.net/ which allows to read zip file.

**Comment by natir** [comment]
I think use [libarchive](https://github.com/libarchive/libarchive) for all compress file management is a better idea : 
- Number of format support
- License is BSD
- Is packaged
- No Qt dependency :)

**Comment by dridk** [comment]
I found this : 
https://github.com/chokkan/seekgzip 

As you said before, random access using seek in a gzip file, is the most important feature we need  !

**Comment by dridk** [comment]
https://github.com/sebastiandev/zipper

**Comment by dridk** [comment]
So, I think we only need 2 dynamics dependency : zlib and htslib.

**Comment by dridk** [comment]
Was pretty hard, but application could be compile now easily from win32. I m deploying directly quazip.dll for this platform . For other , I recompile it from source code using native zlib dependency.
Wait for @ikit to confirm if works on win10.

**Comment by dridk** [comment]
Works  !
