### ISSUE TITLE
Chromsom 19 doesn't not look as expected 

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#39]
Here is the chromosom 19 as it shows from BB.
![arch1](https://cloud.githubusercontent.com/assets/1911063/13670207/d2fc66d8-e6c8-11e5-8c4d-f69c1ba79558.png)
Here is the chromosom from ensembl : 
http://grch37.ensembl.org/Homo_sapiens/Location/View?r=19:49197156-49297156

![arch1](https://cloud.githubusercontent.com/assets/1911063/13670239/02e837b4-e6c9-11e5-8b0d-5719fcf42a04.png)

**Comment by ikit** [comment]
And where is the problem ?

**Comment by dridk** [comment]
You didnt see?
Color are segmented from ensembl
Le 10 mars 2016 21:19, "Olivier Gueudelot" notifications@github.com a
écrit :

**Comment by ikit** [comment]
ok
It's not an error... it seems that in ensembl they didn't use region stain to colorize regions, they just alternate light and dark grey.
The chr19 is composed only with gneg and gpos25 which are too close (regarding the color). But ok, I will reinforce the "darker" of the gpos25...

**Comment by ikit** [comment]
fixed
