### ISSUE TITLE
remove revcomp.h

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#44]
I don't see any reason to have this class. 
Please remove it, and write your code only into Sequence class

**Comment by dridk** [comment]
Developpers are expected , everything from big::core and big::gui are simple class and behave like Qt class .  I mean, I except to have Sequence::reverseComplement () .  I do not want to use another class for this task. 
Regarding other library like Biopython ( Sequence = SeqIo)   , you may want to use a class : big::core::Alphabet .  And use them as a singleton to store your table. ( and also protein AA table)

**Comment by natir** [comment]
Solve by 4d0184cc0d30
