### ISSUE TITLE
selectionChanged is not emitted in Chromosomwidget

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#46]
Do not forget to signal selectionChanged ! 
For instance, when you drag selection area from left or from right. 

emit selectionChanged(chr,start,end).

**Comment by ikit** [comment]
For me it's ok. The emit is done only when the "active" frame is updated (see updateFrame method).
We don't have to emit when we are selecting, dragging et resizing the frame, as we are only moving a "ghost" frame.

**Comment by dridk** [comment]
A agree . The bug come only when you are resize from right or left, and then release click. So, the signal is not emit

**Comment by dridk** [comment]
Procedure : 
- Resize from left 
- Release mouse 
- The signal is not emmited

**Comment by dridk** [comment]
@ikit seems your last commit reopen this issu
