### ISSUE TITLE
Cannot access Sequence methods

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#54]
I excepted to have methods avaible from this way: 

```
    Sequence seq("ACGT");
    qDebug()<<seq.reverseComplement();
```

Not working actually

**Comment by natir** [comment]
Yes it's impossible by design. Sequence is just a typedef because we can't inherite to Qt and STL container, and write a wrapper is long and create bug task. 

But this run : 

``` c++
big::core::Sequence seq("ACGT");
qDebug()<<big::core::sequence::reverseComplement(seq);
```

**Comment by natir** [comment]
I can close this issue @dridk ?

**Comment by dridk** [comment]
Yes.  But i will create a new one for seq->name() et seq->setName ("chr4")
