### ISSUE TITLE
paintRegion should be called by update() 

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#62]
AbstractTrack::paintRegion() should be called each time by update() . 
It seems you have a condition here : https://github.com/BIG-Tools/BigBrowser/blob/master/src/gui/tracks/abstracttrack.cpp#L273 

You should remove it .

**Comment by ikit** [comment]
By default the asynch track manage a cache to avoid to redraw content to often... I agree that it should be more generic to put the default cache management in the paintRegion method, but that mean that all track will have to manage it... no more default management for the cache...
